# https://home-assistant.io/components/sensor.buienradar/
- platform: buienradar
  monitored_conditions:
    - stationname
    - symbol
    - humidity
    - temperature
    - precipitation_forecast_total
